services:
  postgres:
    image: postgres:15-alpine
    container_name: road_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: road_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./road_back/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - road_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serveur de tuiles offline pour Antananarivo
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: road_tileserver
    ports:
      - "8081:8080"
    volumes:
      - ./tiles:/data
    networks:
      - road_network
    command: --verbose --config /data/config.json
    restart: unless-stopped

  backend:
    build:
      context: ./road_back
      dockerfile: Dockerfile
    container_name: road_backend
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - road_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/road_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./road_front
      dockerfile: Dockerfile
    container_name: road_frontend
    networks:
      - road_network
    ports:
      - "5173:5173"

networks:
  road_network:
    driver: bridge

volumes:
  postgres_data:
